name: VytherTokens
version: 1.0
main: me.jadenp.vythertokens.VytherTokens
api-version: 1.17
authors: [ Not_Jaden ]
description: A simple tokens system
softdepend:
  - PlaceholderAPI
commands:
  token:
    usage: /token
    description: to add and remove tokens
    aliases:
      - tokens
      - nottokens
      - ntokens
permissions:
  vythertokens.admin:
    description: ability to add and remove tokens
    default: op
